SELECT id,
    name,
    description,
    status,
    start_date,
    end_date,
    progress,
    creator_id,
    assignee_id,
    milestones,
    this_week_work,
    next_week_plan,
    create_time,
    update_time
FROM projects